version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: speechup_mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: "no"